gene_expression_matrix: SERGIO_DS4_net0_gene_expression_matrix.csv
ground_truth: SERGIO_DS4_net0_ground_truth.csv
raw_edges: ~
edge_features: ~
model: ~
model_assessment: ~
predicted_edges: ~
cict_raw_edge_col: Pearson
