gene_expression_matrix: /home/syz248/CICTv2/inst/extdata/SERGIO_DS4_net0_gene_expression_matrix.csv
ground_truth: /home/syz248/CICTv2/inst/extdata/SERGIO_DS4_net0_ground_truth.csv
raw_edges: ~
edge_features: ~
model: ~
model_assessment: ~
predicted_edges: ~
cict_raw_edge_col: Pearson
